name: allofcar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # [NEW] Required for DatePicker
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  google_fonts: ^6.3.3
  image_picker: ^1.2.1
  intl: ^0.20.2
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.1.0
  url_launcher: ^6.3.2
  html: ^0.15.6
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  flutter_dotenv: ^6.0.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  googleapis_auth: ^1.6.0
  translator: ^1.0.0 # [NEW] Google Translate functionality
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon_android_black.png"
  image_path_ios: "assets/images/icon_ios_fixed.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_android_black.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # Resim klasörünü buraya tanıttık:
  assets:
    - assets/images/
    - .env